FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/server/package.json ./apps/server/
COPY packages/ ./packages/

RUN pnpm install --filter server...

COPY apps/server ./apps/server

WORKDIR /app/apps/server

CMD ["pnpm", "dev"]
